GET http://localhost:3000/logs
###

GET  http://localhost:3000/produits/601ac7313a308649146fbe02

###

POST  http://localhost:3000/ingredients
Content-Type: application/json

{
    "name" : "test",
    "score" : "0"
}